version: "3"
services:
  redis-server:
    container_name: node-jwt-redis
    image: redis:7
  node-app:
    container_name: node-jwt-app
    build: .
    environment:
      - SECRET=${SECRET}
      - REDIS_URL=redis://redis-server:6379
    depends_on:
      - redis-server
